### ISSUE TITLE
Sign in/Sign up flow

### ISSUE THREAD

**Issue by duckinator** [gratipay/gratipay.com#1894]
This is a general issue about the entire onboarding process, for implementing the design that was discussed at the retreat.

Here are some issues that we want to resolve while implementing this new onboarding process:
- [x] Persist tip value through sign up process (#1836).
- [ ] Fix sign out to reclaim flow (#34).
- [ ] Prompt user to accept or decline new tips at sign-up or first login (#301).
- [ ] Split up registration process for payins and payputs (#321).
- [ ] Always direct to user's page after sign-up (#697).
- [ ] Improve click/hover behavior with sign-in dropdown (#1289).

TODO: Figure out how to best combine this and #1167 ("revamp checkout workflow").
