### ISSUE TITLE
Set up pagerduty for alerting and accountability

### ISSUE THREAD

**Issue by patcon** [gratipay/gratipay.com#2072]
In setting up hubot and preparing for him to be given responsibility, I feel we need a good way to make sure that if he ever goes down, someone will be alerted right away, and there will be chain of responsibility if that someone is unavailable (ie. an on-call schedule and escalation policy).

I've had experience with PagerDuty in the past, and they are a great tool, trusted by other great product companies ([GitHub being one of them](https://github.com/github/hubot-scripts/pull/858)).

I personally wouldn't feel comfortable giving hubot any future control unless he's got properly monitored with alerting in place :) I'm really excited to work on implementing on-call schedules and rotations for other critical monitoring areas of Gittip. This will help us distribute responsibility to the right people (and away from Chad). And if you're on an on-call schedule, Gittip gets a little more real for you, which is a good thing :)

Evolving vendor policy: https://github.com/gittip/building.gittip.com/issues/15
Roobot PagerDuty setup issue: https://github.com/gittip/roobot/issues/8
# Todo
- [ ] Create user for @whit537 
- [ ] Create user for @greggles 
- [ ] Create user for @bruceadams
- [ ] Create user for @zwn
- [ ] set up general downtime notifcations via uptimerobot (make sure schedule matching actual availability)
  - @whit537
  - @zwn 
- [ ] configure security@gittip.com
  - ~~@whit537~~ 
  - @patcon
  - @greggles
  - @bruceadams 
  - @zwn
