### ISSUE TITLE
Start tracking user events

### ISSUE THREAD

**Issue by patcon** [gratipay/gratipay.com#2367]
So now that we're anonymously tracking users (#2334) via session ID or participant ID (if available), we can start adding tracking events to help us understand user behaviour and funnels:
https://segment.io/docs/tutorials/quickstart-analytics.js/#step-3-track-actions

This might end up being a meta issue, but thought it might be nice to have a place to brainstorm helpful events we might want to track.
### Proposed
- [ ] signed up
- [ ] deactivated account
- [ ] logged in
- [ ] logged out
- [ ] connected social account X
- [ ] disconnected social account X
- [ ] connected credit card
- [ ] connected bank account
- [ ] disconnected credit card
- [ ] disconnected bank account
- [ ] added bitcoin address
- [ ] added email
- [ ] added statement
- [ ] updated funding goal
- [ ] sent venmo gift
- [ ] added gift
- [ ] removed gift
- [ ] increased gift
- [ ] decreased gift
- [ ] earmarked gift
- [ ] created community
- [ ] joined community
- [ ] left community
- [ ] became team account
- [ ] became individual account
- [ ] joined team
- [ ] left team
- [ ] upped take
- [ ] lowered take
- [ ] show API key
- [ ] recreate API key
- [ ] set funding goal
- [ ] edit funding goal (are they getting more ambitious? Less?)

cc: @clone1018 
##

**Comment by whit537** [comment]
Closing in light of our decision to [shut down Gratipay](https://gratipay.news/the-end-cbfba8f50981).

Thank you all for a great run, and I'm sorry it didn't work out! 😞  💃
