### ISSUE TITLE
Rewrite payday

### ISSUE THREAD

**Issue by Changaco** [gratipay/gratipay.com#2508]
Opening an issue as discussed in [IRC](https://botbot.me/freenode/gittip/msg/16424742/).

Here are the main goals of the rewrite:
- make it fast: having it run in under 10 minutes would be nice
- make it safe: we've had failures in the past, we need to do better, it's money we're handling here
- reduce the amounts of fees and escrow by not charging credit cards when we don't actually need to

And here's my checklist:
- [x] solve #1486 by implementing [card holds](https://docs.balancedpayments.com/1.1/api/card-holds/)
- [x] do stuff directly in SQL instead of making a lot of round trips between the DB and the python code:
  - [x] update stats in a single request at the end of payday
  - [x] rewrite the transfer of tips and takes in SQL
- [x] optimize the SQL (`explain analyze` FTW)
- [x] do payin in a single transaction
- [x] fix #1853
- [x] make sure we don't get out of sync with Balanced (#213)
- [x] make sure we don't transfer tips to participants who don't want to receive them (#916)
- [x] investigate #2537
- [x] handle payout failures (#1811)
- [x] parallelize the Balanced API requests

(Am I missing other issues that the payday rewrite should fix ?)
