### ISSUE TITLE
Complete take_over

### ISSUE THREAD

**Issue by Changaco** [gratipay/gratipay.com#2630]
Reticketed from #1948. We've already taken steps towards completing `take_over`, this issue is to keep track of what's still missing:
- [x] fix the merge UI
- [ ] merge ui should give you the option to make the other account primary (was #675)
- [ ] merge statement (was #834)
- [ ] merge exchange routes (was #941)
- [x] ~~archived accounts should be removed from teams (was #1920)~~ (fixed in #2718)
- [ ] merge email addresses
##
