### ISSUE TITLE
discuss roadmap based on information architecture

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3220]
Here's an IA that I did (click to rotate properly?):

![ia](https://cloud.githubusercontent.com/assets/134455/6477192/5910d174-c1ee-11e4-9253-545ca8594832.jpg)

**Comment by whit537** [comment]
Some things I see going on when I consider the above map:

 - [x] Since drawing this, we've added the dashboard as the first item under profile (https://github.com/gratipay/gratipay.com/pull/2809). "Home" now refers to the unauthenticated homepage, and the authenticated homepage is the dashboard.
 - [ ] CC/BA really want to be somewhere under Profile > Account. But how would this relate to a modal (#1167)?
 - [ ] We should fold For into Explore as part of downgrading communities to tags (#3127).
 - [ ] Explore and Search should be integrated one with the other (#3221)).
 - [ ] I see nice tables as a potential unifying element across the site. We should be able to write a nice table library (parallel to charts.js) that works for: explore, search, members, receiving, giving, history, events, and elsewhere teams (#3222).

**Comment by Changaco** [comment]
Account probably shouldn't be under Profile. I'm talking about the UI, not necessarily the URLs. You should have access to your account settings from the top nav. The subnav of the Profile page shouldn't contain Dashboard, History, Widgets and Account (except maybe for admins).

**Comment by whit537** [comment]
@Changaco You would put History and Widgets under Account?

**Comment by Changaco** [comment]
> You would put History and Widgets under Account?

In the UI yes, I would link to them from a dropdown in the top nav, and hide them from the Profile subnav (except for admins).

**Comment by whit537** [comment]
What's the relationship between Profile and Account? What do those mean?

@rummik has suggested before changing Account to Options or Settings.

**Comment by Changaco** [comment]
> What's the relationship between Profile and Account? What do those mean?

Profile is the public subset of Account, it's what others see. Currently that's 2 or 3 pages: Profile, Receiving, and Members. #3112 will add Giving.

**Comment by whit537** [comment]
> Profile is the public subset of Account

Okay, so Account would look like this?

```
Account
  Profile
    Basic Info
      Statement
      Funding Goal
      Teams
      Communities
      Social Profiles
      Other Receiving Options
    Giving
    Receiving
    Members
  History
  Widgets
    Button
    Badge
    Giving & Receiving Widgets
  Settings
    Username
    Account Type
    Available Money
    Adding Money
    Withdrawing Money
    Email Addresses (Private)
    API Credentials
    Privacy
    Notifications
    Close
    Events
```

**Comment by whit537** [comment]
Settings looks messy, maybe Basic Info, too.

**Comment by whit537** [comment]
Also, API Credentials isn't a setting that I can change. Maybe we should fold it together with Widgets? Also, "Embed" is more common than "Widget":

https://developers.facebook.com/docs/plugins/embedded-posts
https://dev.twitter.com/web/embedded-tweets
https://medium.com/@Medium/embed-medium-anywhere-3eaed64aed8a
http://blog.vine.co/post/55514921892/embed-vine-posts
http://embed.ly/

```
Account
  Profile
    Basics
      Statement
      Funding Goal
      Teams
      Tags
      Social Profiles
      Other Receiving Options
    Giving
    Receiving
    Members
  Embeds & API
    Button
    Badge
    Giving & Receiving Widgets
    API Credentials
  Funding Instruments
  Settings
    Basics
      Username
      Account Type
      Available Money
    Email
      Addresses
      Notifications
    Privacy
    Close Account
  Events
```

**Comment by Changaco** [comment]
The API key is a setting you can change, it is in fact the account's password, the web UI just doesn't have a form to log in with it.

**Comment by whit537** [comment]
You can regenerate it, is that what you mean by "change"? You can't set it to something arbitrary, like you can with a password.

**Comment by whit537** [comment]
Eventually I think we want multiple API keys.

**Comment by Changaco** [comment]
I don't think we want to switch to Embed, because the widgets don't actually embed any user-generated content like a tweet or a blog post.

**Comment by whit537** [comment]
> I don't think we want to switch to Embed, because the widgets don't actually embed any user-generated content like a tweet or a blog post.

Okay, but they do embed HTML elements into another page.

**Comment by Changaco** [comment]
> Eventually I think we want multiple API keys.

I think it's OAuth tokens you want.

**Comment by whit537** [comment]
Our "widgets" aren't really widgets:

> In computing, a web widget is a software widget for the web. It's a small application with limited functionality that can be installed and executed within a web page by an end user. [...]
>
Widgets often take the form of on-screen devices such as clocks, event countdowns, auction-tickers, stock market tickers, flight arrival information, daily weather etc..

http://en.wikipedia.org/wiki/Web_widget

**Comment by whit537** [comment]
> I think it's OAuth tokens you want.

Sure. I have in mind GitHub's model, which [conflates the two](https://developer.github.com/v3/auth/#basic-authentication).

**Comment by whit537** [comment]
I think we should evolve Events into a user-accessible Audit Log.

**Comment by whit537** [comment]
Let's move the Embed vs. Widget conversation to https://github.com/gratipay/inside.gratipay.com/issues/125.

**Comment by Changaco** [comment]
Proposal (changes marked with asterisks):

```
Account
  Profile
    *Presentation*
      Statement
      Funding Goal
      Teams
      Tags
      Social Profiles
      Other Receiving Options
    Giving
    Receiving
    Members
  *Embeds/Widgets* (no API stuff)
    Button
    Badge
    Giving/Receiving
  *Balance & History*
  Settings
    Basics
      Username
      *Password* (replaces "API Credentials")
      Account Type
    Funding Instruments
    Email
    *Notifications* (doesn't go under Email because it also handles on-site notifs)
    Privacy
    Close Account
```

**Comment by whit537** [comment]
Inverting Profile an Account reticketed as #3236 and noted above, at https://github.com/gratipay/gratipay.com/issues/3220#issuecomment-77089247.

!m @Changaco

**Comment by whit537** [comment]
`Presentation` is awkward, imo. `Profile > Basics` would be parallel to `Settings > Basics`.

**Comment by whit537** [comment]
`*Password* (replaces "API Credentials")`

Interesting. Will I be able to have multiple passwords?

**Comment by Changaco** [comment]
> `Presentation` is awkward, imo. `Profile > Basics` would be parallel to `Settings > Basics`.

To me "Profile Basics" looks awkward, and I don't see why we would want a parallel to Settings.

> Interesting. Will I be able to have multiple passwords?

I don't see any use for that as long as we don't have permission scopes to attach to them.

**Comment by whit537** [comment]
> I don't see why we would want a parallel to Settings.

The reason to keep them parallel is to make it easier for the user to understand what each is, by reference to the other. Under About we use Overview in this regard.

Facebook uses "General":

![screen shot 2015-03-09 at 2 26 34 pm](https://cloud.githubusercontent.com/assets/134455/6561540/69376044-c668-11e4-91f1-16c832f85ac9.png)

**Comment by whit537** [comment]
> I don't see any use for that as long as we don't have permission scopes to attach to them.

Okay, let's carry this over to #1052.

**Comment by whit537** [comment]
Gmail also uses General:

![screen shot 2015-03-10 at 8 40 06 am](https://cloud.githubusercontent.com/assets/134455/6575014/23b9191a-c701-11e4-88a7-53cb69718d7c.png)

**Comment by whit537** [comment]
Twitter uses Account (and the word "basic" in help text):

![screen shot 2015-03-10 at 8 41 40 am](https://cloud.githubusercontent.com/assets/134455/6575042/6a24b594-c701-11e4-87ad-27779d6848e0.png)

**Comment by whit537** [comment]
[IRC](https://botbot.me/freenode/gratipay/2015-03-11/?msg=33918026&page=1)

**Comment by whit537** [comment]
Profile/Account discussion continued on #3236.

**Comment by whit537** [comment]
The work on #3236 is leading into discussion about nav and layout: #3258.

**Comment by whit537** [comment]
We're discussing the purpose of this ticket over at https://github.com/gratipay/gratipay.com/issues/3258#issuecomment-82351843.

**Comment by whit537** [comment]
*Deleting from #3258 and reposted here ...*

@Changaco A couple times now you've made a distinction between UI and URLs (https://github.com/gratipay/gratipay.com/issues/3220#issuecomment-77164012, https://github.com/gratipay/gratipay.com/issues/3236#issuecomment-81970811). I don't think that's a helpful distinction. We can't not have URLs, so we need to design them at some point. Furthermore, they're visible to users, and, like it or not, [users do in fact use them](http://www.nngroup.com/articles/url-as-ui/). I think we should think of URLs as a subset of UI, that is, as one aspect of encoding our information architecture.

**Comment by whit537** [comment]
I've added this ticket to the top of http://inside.gratipay.com/big-picture/product. This ticket should result in a significant revision of that page.

**Comment by whit537** [comment]
I covered a desk with paper this afternoon, trying to wrap my head around what we need to do on this ticket. A couple teaser photos ... user goals front and center, flanked by other major concerns, with IA along the back.

![photo on 3-19-15 at 6 53 pm 2](https://cloud.githubusercontent.com/assets/134455/6742829/817753d6-ce69-11e4-85b8-ee06c1da8c9c.jpg)

![photo on 3-19-15 at 6 57 pm](https://cloud.githubusercontent.com/assets/134455/6742874/df235962-ce69-11e4-8676-afceac27d915.jpg)

![photo on 3-19-15 at 6 54 pm 2](https://cloud.githubusercontent.com/assets/134455/6742836/8c1cadfe-ce69-11e4-967f-5bd969ad9b79.jpg)

![photo on 3-19-15 at 6 56 pm](https://cloud.githubusercontent.com/assets/134455/6742878/e6011c7e-ce69-11e4-8d72-9cb6fdab0041.jpg)

![photo on 3-19-15 at 6 57 pm 2](https://cloud.githubusercontent.com/assets/134455/6742881/ee1f5d76-ce69-11e4-9d49-5e168ff277eb.jpg)

![photo on 3-19-15 at 6 57 pm 3](https://cloud.githubusercontent.com/assets/134455/6742882/f0de6b24-ce69-11e4-9462-d300db90a206.jpg)

**Comment by whit537** [comment]
See https://github.com/gratipay/inside.gratipay.com/issues/163 for follow-on conversation. I expect to use the new http://inside.gratipay.com/big-picture/product page to talk about intent when introducing PRs into the pipeline.
