### ISSUE TITLE
announce the new system

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3419]
Reticketing from @webmaven at https://github.com/gratipay/gratipay.com/issues/3390#issuecomment-101873253.

**Comment by mattbk** [comment]
Includes updating the front page at all?

**Comment by ehmatthes** [comment]
> Includes updating the front page at all?

It has to; Gratipay needs to pull people in, both project leaders and potential funders.

**Comment by whit537** [comment]
+1 from @kaguillera on #3428:

> I suggest apart from answering this comment/thread/issue directly that it should be emailed/posted/blogged/tweeted/etc somewhere so that users like myself know what is going on.

**Comment by whit537** [comment]
I put up a simple notice in #3452. This ticket is for a proper blog post.

**Comment by whit537** [comment]
Here's a draft: https://medium.com/@Gratipay/2453d3c53077 (still very much in-process).

**Comment by whit537** [comment]
Blocking on:

 - [ ] turning subscriptions on in the UI (#3432)
 - [ ] self-serve PayPal (#2387)
 - [ ] require identity for PayPal (easy enough, but depends on #3458)
 - [ ] split out revenue model question (#3456)

**Comment by webmaven** [comment]
Left some feedback on the draft.

**Comment by whit537** [comment]
Thanks! :)

**Comment by whit537** [comment]
#3458 is too much work to get done before tomorrow. :-( I'm striking it from the punchlist.

**Comment by whit537** [comment]
Ready for final review: https://medium.com/@Gratipay/2453d3c53077.

**Comment by clone1018** [comment]
@whit537 Every team link in that post 404's for me.

**Comment by whit537** [comment]
@clone1018 Yeah, pending #3464&mdash;added to [punchlist](https://github.com/gratipay/gratipay.com/issues/3419#issuecomment-103870467).

**Comment by whit537** [comment]
Outta time. :-(

I'll be back later tonight ...

**Comment by whit537** [comment]
Okay! We have PRs open for #3432 and #3456. Once we land those we can give https://medium.com/@Gratipay/2453d3c53077 a once-over and then publish. Then we can follow up with lots of users who are waiting for this post.

**Comment by whit537** [comment]
We're live!

https://medium.com/gratipay-blog/gratipay-2-0-2453d3c53077

:dancer:

**Comment by whit537** [comment]
#3476 and https://twitter.com/Gratipay/status/601565078547083265

**Comment by whit537** [comment]
I followed up with everyone in our support queue and in my private email.

**Comment by webmaven** [comment]
Was the feedback I gave on the post helpful or just distracting (I can't see what I said anymore, or if you responded)?

**Comment by whit537** [comment]
@webmaven Helpful! I believe I incorporated all or almost all of your suggestions, though further editing may have obscured that.

**Comment by whit537** [comment]
Reopening to send an email blast. We did this for "[Gratipocalypse](https://medium.com/gratipay-blog/gratipocalypse-42fd0ec0d9e8)", so we should do the same for "[Gratipay 2.0](https://medium.com/gratipay-blog/gratipay-2-0-2453d3c53077)" to maintain parallelism.

**Comment by rohitpaulk** [comment]
> We did this for "Gratipocalypse", so we should do the same for "Gratipay 2.0" to maintain parallelism.

+1. A friend of mine asked me whether Gratipay is still processing payments, coz he 'didn't receive an email after the Gratipocalypse one'

**Comment by whit537** [comment]
Done in #3510.
