### ISSUE TITLE
Clean up exchanges

### ISSUE THREAD

**Issue by kaguillera** [gratipay/gratipay.com#4442]
-------------------------------

✈️  **This is the flight deck for the [Clean up exchanges](https://github.com/orgs/gratipay/projects/20?fullscreen=true) project.** ✈️ 

-------------------------------

Due to bad schema design we have missing values for some fields in our `exchanges` and `exchange_routes` tables. We use either `unknown` or `NULL` to represent this missing info (we started using `unknown` in https://github.com/gratipay/gratipay.com/pull/3975 in order to make querying easier).

| table | field | value |
|:------|:------|:-------|
| `exchanges` | `ref` | `NULL` |
| `exchanges` | `status` | `unknown` |
| `exchange_routes` | `network` | `unknown` |

## Todo

- [ ] determine whether `network` is corrupt—https://github.com/gratipay/gratipay.com/issues/4442#issuecomment-305864193
- [x] determine whether we are still leaking
  - [x] `ref`—https://github.com/gratipay/gratipay.com/issues/4442#issuecomment-305859075
  - [x] `status`—https://github.com/gratipay/gratipay.com/issues/4442#issuecomment-305868068
  - [x] `network` and `address`—https://github.com/gratipay/gratipay.com/issues/4442#issuecomment-305864193
- [x] add `ref` to record an exchange -- #4518  
- [x] plug last remaining leak: `ref` under MassPay —https://github.com/gratipay/gratipay.com/pull/3912#issuecomment-305855944
-- #4518 
- [ ] backfill old records
  - [ ] `ref`
  - [ ] `status`
  - [ ] `network` and `address`
- [ ] constrain field for non-{`NULL`,`unknown`}
  - [ ] `ref`
  - [ ] `status`
  - [ ] `network`

## Original

Confused. So far.
- There is no payday log for payday 0, payday 1, payday 2
- The payday log for payday run on 2012-06-22 is no where to be found
- There are exchange records in the exchange table for all of the above paydays assuming that 
       - Payday 0 was run on 2012-06-01
       - Payday 1 was run on 2012-06-08
       - Payday 2 was run on 2012-06-15 which according to `gittip-3.log` (payday logs it was)
       - Payday 3 was run on 2012-06-22 but no log exist but there are records of exchanges in the `exchanges` table
       - Payday 4 was run on 2012-06-29 but is actually recorded in `gittip-4.log`
- Even though there are exchange records for all the paydays mentioned above not all the records for all the transactions exist in the `exchanges` table. That is to say for example in payday logs for the payday run on 2012-06-15 ( recorded in gittp-3.log) 18 people were charged ( I am assuming via samurai since that was the vender we were using at that time) but only 3 exchanges were recorded. This possibly happened because of a database error since I am seeing some error statements at the end of the log file.

-------------------------------

✈️  **This is the flight deck for the [Clean up exchanges](https://github.com/orgs/gratipay/projects/20?fullscreen=true) project.** ✈️ 

-------------------------------

**Comment by kaguillera** [comment]
Thus the routes (network) for this first set of records should be samurai

**Comment by whit537** [comment]
Ref: .https://github.com/gratipay/gratipay.com/pull/3912

**Comment by kaguillera** [comment]
The exchange records for payday 0, payday 1 and payday 2 run on 2012-06-01, 2012-06-08 and 2012-06-15 respectively. There is just one record that is out of place. 
I am thinking that for those initial 16 exchanges and 13 exchange_route we can manually update them. We know that the network is Samurai...but what do we put for the address and ref? Do we have any way of getting it or should be generate a fake one like in the script? I suggest that we generate a fake one as the backfill script does.

**Comment by kaguillera** [comment]
For the Stripe exchanges
exchanges.route = exchange_routes.id
exchanges.status = stripe transaction status
exchanges.ref = transaction_id from stripe (e.g. `ch_7h*********cP`)

exchange_routes.network = stripe
exhcange_routes.address = stripe customer_id (e.g. `cus_1d3*********4z`)

Were have all of the necessary information in the logs directory under misc/3912/year/month/stripe. 
So what went wrong why is the network `unknown` and the address `n/a` for some some exchange routes.

**Comment by kaguillera** [comment]
in the `exchange_routes` table I have there are not `stripe` network value is it possible that all the `unknown` values are actually `stripe` exchange_routes?

**Comment by kaguillera** [comment]
Turns out that the `unknown` could also be `samurai` but why is this happening.

**Comment by kaguillera** [comment]
And also `balanced-ba` exchange_route. what went wrong. Time to check the code I guess.

**Comment by kaguillera** [comment]
Additionally I want look more closely at the error statements at the end of the `gittip-3.log` file

**Comment by kaguillera** [comment]
There seem to be no relation between the errors at the end of `gittip-3.log` and the three successfully recorded records in the `exchanges` table. I was hoping that the users that showed up in the errors were the transactions that were not recorded but there is a user listed in the error that was successfully recorded in the `exchanges` table.  
It could be that the transactions recorded were the only successful ones. The log `gittip-3.log` does not specify if the transaction was successful or not. 
Moving on to look at the code that insert or updated the route and ref values in the exchanges table.

**Comment by kaguillera** [comment]
Not finding where we introduced the exchange_routes. 😱

**Comment by kaguillera** [comment]
So IRL @whit537 just reminded me that I made the `unknown` when I was redoing the dashboard `reconciliation.spt` page. 😱  😭

**Comment by kaguillera** [comment]
Ok so here is the plan. Correct the `unknown` `exchange_routes` and then make backfill the references. 

How do I correct the `exchange_routes`?
I am thinking I could use the payday logs along with the `exchanges` table to match participants the transactions and thus networks. This should work since pre gittp-8.log we only used two `payment_network`s namely samurai and Stripe. and after that we specified in the logs which `payment_network` we were charging the `participant` on. Thus from that I can make routes for the `participant`s and update the `exchanges` with that `route_id` 
Theoretically!

**Comment by kaguillera** [comment]
Current `payment_net` values

```
    network
--------------
 balanced-ba
 balanced-cc
 paypal
 bitcoin
 braintree-cc
 cash
 transferwise
 dwolla
 unknown
(9 rows)
```

**Comment by kaguillera** [comment]
https://github.com/gratipay/gratipay.com/pull/3807  & https://github.com/gratipay/gratipay.com/issues/2779 - Back filled the exchanges and created routes for Balanced transactions when we were refunding and/or Balanced shutdown. 

NB: In the payday log files we started recording `success` in the on the 4th payday `gittip-4.log`

This [`match-stripe.py`](https://github.com/gratipay/gratipay.com/blob/95162c2eaaf4b50b486a45e469addd9555428d9b/match-stripe.py) is a script to match Stripe transactions with exchanges to produce the input file for the [`backfill.py`](https://github.com/gratipay/gratipay.com/blob/95162c2eaaf4b50b486a45e469addd9555428d9b/backfill.py) script.

But the issue [here](https://github.com/gratipay/gratipay.com/pull/3912#issuecomment-182531679) is 
> The problem we're up against is ... usernames as primary key (#835). 😊

> The way we log username changes, we don't record the old username, only the new one. This makes it impossible to trace back to what username a participant had at a particular point in time. We do have old database snapshots we could look at, but we didn't add user id until late enough that an old snapshot wouldn't help us map old username to current user id anyway.

But I think that we can backfill what we can and figure out how to resolve this issue after. There should only be a small amount of these cases. 

For now we can assume that all recorded transaction/exchanges with a `null` or `unknown` were successful cf (https://github.com/gratipay/gratipay.com/pull/3912#issuecomment-194500173)

After we have made finished backfilling we can always use the payday log files for payday #4 and onward to correct the status if necessary.

**Comment by kaguillera** [comment]
NB [The previous plan](https://github.com/gratipay/gratipay.com/pull/3912#issuecomment-194485146)

[`match-balanced.py`](https://github.com/gratipay/gratipay.com/blob/867b8fcac9c1b381852d158b064f87cf74923523/match-balanced.py#L269)

Issues with [data corruption](https://github.com/gratipay/gratipay.com/pull/4342#issuecomment-283450229) that I need to research next before we go ahead...tomorrow

**Comment by kaguillera** [comment]
`exchanges` record

| id | timestamp | amount | fee | participant | status | route |
| --- | --- | --- | --- | --- | --- | --- |
| 327 | 2012-07-27 20:54:01.856078+00 | 9.32 | 0.68 | bekishore | succeeded | 8219 |

`exchange_route` record for the above exchange

| id | participant | network | address | is_deleted |
| --- | --- | --- | --- | --- |
| 8219 | 9815 | braintree-cc | CC3xxxxxxxxxxxxxxxlw | f |

Note the `timestamp`  date of the exchange. We did not start using braintree until some time in 2015 after the Balanced shutdown s clearly this is wrong. Additionally in the payday log for that date it it records the following...
`pid-24223 thread-140735091989696 (MainThread) Charging bekishore 1000 cents ($1.00 + $0.36 fee = $1.36, round     ed up to $10.00) on Balanced ... succeeded.`

Not sure how that happened. The point I am making is that besides having to backfill `exchanges` and `exchange_routes` we will have to do an audit/reconciliation/corrects possibly using the payday logs. I think that we should do this in a separate PR after we have done the `backfill`

**Comment by kaguillera** [comment]
So my conclusion after researching is that we are on the [right track](https://github.com/gratipay/gratipay.com/pull/3912#issuecomment-194485146) and we should continue implementing the back fill the way we were with a few changes. The main change is that we create new `exchange_route`s for `exchanges` where the `exchange_route` network field is `unknown`

Thus the next step is to add `samurai` and `stripe` to the payment_net ENUM and then follow the steps [here](https://github.com/gratipay/gratipay.com/pull/3912#issuecomment-194485146)

**Comment by kaguillera** [comment]
Copied from  [here](https://github.com/gratipay/gratipay.com/pull/3912#issuecomment-194485146)

##### How to Backfill Exchanges

For each month in https://github.com/gratipay/finances/issues/3:
1. generate input CSVs for all vendors that we started using in the given month; for each vendor:
   1. export CSVs for all data for the given vendor—these are our **raw input CSVs**
   2. write one-off scripts to split up raw input CSVs into one CSV per month in the `3912` [directory](https://github.com/gratipay/logs/tree/backfill/misc/3912) in the `logs` repo (`backfill` branch; prefix with `_` to be ignored by `backfill.py`)—these are the **input CSVs**
2. write a `match-{foo}.py` script to generate `3912/YYYY/MM/foo` files (no extension! `{foo}` matches a payment network in the `ENUM` in the database)—these are our **match CSVs**
3. run `backfill.py` to backfill all `exchanges` and `exchange_routes` needed for the given month based on the match CSVs
4. [reconcile the books](https://github.com/gratipay/finances#how-this-repo-is-organized) for the given month

**Comment by kaguillera** [comment]
Based on the current structure of the [`backfill`](https://github.com/gratipay/logs/tree/backfill/misc/3912) branch I believe we have to do step 2 for the `_balanced` files. 

Here goes...

**Comment by whit537** [comment]
We plugged one `ref` leak in #4361 but now it [looks like](https://github.com/gratipay/gratipay.com/pull/3912#issuecomment-305855944) we have another, in MassPay.

Do any of the other three still leak?

**Comment by whit537** [comment]
Are we leaking `NULL` routes?

**Comment by whit537** [comment]
No! It has a `not null` constraint and also does not accept `unknown`.

**Comment by whit537** [comment]
`status` and `network` both have a `not null` constraint, but do accept `unknown`. Are we leaking `status`?

**Comment by whit537** [comment]
Actually, back up: we've already backfilled all exchanges with a `route`, so we can remove that as a direct concern. Instead the pertinent field is `network` ... and `address`!

```
gratipay::DATABASE=> select count(*) from exchange_routes where network = 'unknown';
┌───────┐
│ count │
├───────┤
│  1626 │
└───────┘
(1 row)

gratipay::DATABASE=> select count(*) from exchange_routes where address = 'n/a';
┌───────┐
│ count │
├───────┤
│  1626 │
└───────┘
(1 row)

gratipay::DATABASE=>
```

**Comment by whit537** [comment]
Based on a review of ...

```
gratipay::DATABASE=> select id, network from exchange_routes order by id desc limit 1000;
```

... I believe we're no longer leaking `network` (or `address`). But!

What about potentially erroneous networks? I.e., `braintree-cc` per https://github.com/gratipay/gratipay.com/pull/3912#issuecomment-283452228 &rarr; https://github.com/gratipay/gratipay.com/pull/4342#issuecomment-283450229.

**Comment by whit537** [comment]
Here's the end of the `network` leak:

```
gratipay::DATABASE=> select id, network, address != 'n/a' have_address from exchange_routes order by id desc offset 488 limit 20;
┌───────┬──────────────┬──────────────┐
│  id   │   network    │ have_address │
├───────┼──────────────┼──────────────┤
│ 14384 │ bitcoin      │ t            │
│ 14383 │ paypal       │ t            │
│ 14382 │ paypal       │ t            │
│ 14381 │ paypal       │ t            │
│ 14380 │ braintree-cc │ t            │
│ 14379 │ braintree-cc │ t            │
│ 14378 │ bitcoin      │ t            │
│ 14377 │ bitcoin      │ t            │
│ 14376 │ paypal       │ t            │
│ 14375 │ bitcoin      │ t            │
│ 14374 │ unknown      │ f            │
│ 14373 │ unknown      │ f            │
│ 14372 │ unknown      │ f            │
│ 14371 │ unknown      │ f            │
│ 14370 │ unknown      │ f            │
│ 14369 │ unknown      │ f            │
│ 14368 │ unknown      │ f            │
│ 14367 │ unknown      │ f            │
│ 14366 │ unknown      │ f            │
│ 14365 │ unknown      │ f            │
└───────┴──────────────┴──────────────┘
(20 rows)
```

and here's the end of the `status` leak (waaay back!):

```
gratipay::DATABASE=> select timestamp, status from exchanges where status='unknown' order by timestamp desc limit 10;
┌───────────────────────────────┬─────────┐
│           timestamp           │ status  │
├───────────────────────────────┼─────────┤
│ 2014-09-19 20:28:57.098478+00 │ unknown │
│ 2014-09-18 19:39:30.573582+00 │ unknown │
│ 2014-09-18 18:41:58.481287+00 │ unknown │
│ 2014-09-17 19:11:46.682704+00 │ unknown │
│ 2014-09-11 15:13:11.663196+00 │ unknown │
│ 2014-09-11 15:13:10.232116+00 │ unknown │
│ 2014-09-11 15:13:08.634617+00 │ unknown │
│ 2014-09-11 15:13:07.118274+00 │ unknown │
│ 2014-09-11 15:13:03.453589+00 │ unknown │
│ 2014-09-11 15:13:01.812733+00 │ unknown │
└───────────────────────────────┴─────────┘
(10 rows)

gratipay::DATABASE=>
```

**Comment by whit537** [comment]
Yeah, this doesn't look right.

# Braintree

```
gratipay::DATABASE=> select substring(date_trunc('year', timestamp)::text from 0 for 5) as year, count(timestamp) from exchanges e join exchange_routes er on e.route = er.id where network='braintree-cc' group by date_trunc('year', timestamp) order by year;
┌──────┬───────┐
│ year │ count │
├──────┼───────┤
│ 2012 │   467 │
│ 2013 │  5115 │
│ 2014 │ 14362 │
│ 2015 │  8576 │
│ 2016 │  2658 │
│ 2017 │  1075 │
└──────┴───────┘
(6 rows)
```

# Balanced

```
gratipay::DATABASE=> select substring(date_trunc('year', timestamp)::text from 0 for 5) as year, count(timestamp) from exchanges e join exchange_routes er on e.route = er.id where network='balanced-cc' group by date_trunc('year', timestamp) order by year;
┌──────┬───────┐
│ year │ count │
├──────┼───────┤
│ 2012 │   377 │
│ 2013 │  2172 │
│ 2014 │  4269 │
│ 2015 │   600 │
│ 2016 │    63 │
└──────┴───────┘
(5 rows)

gratipay::DATABASE=>
```

**Comment by whit537** [comment]
As expected, there is no `braintree -i` in the payday logs until https://github.com/gratipay/gratipay.com/issues/3486.

**Comment by whit537** [comment]
But I do find `braintree` files under https://github.com/gratipay/logs/tree/231a5f26a6acebf77f5adc1fb1eb98b0d8b86222/misc/308/raw/balanced/refund ... :thinking:

**Comment by whit537** [comment]
The first transactions I find in the Braintree dashboard are on May 29, 2015, which is #3486. See esp. https://github.com/gratipay/gratipay.com/issues/3486#issuecomment-106706837:

![screen shot 2015-05-29 at 2 27 46 am](https://cloud.githubusercontent.com/assets/134455/7877504/55ddd952-05aa-11e5-9cad-d0e006bdc4b7.png)

**Comment by whit537** [comment]
So at this point my best hunch is that I made a mistake during gratipay/inside.gratipay.com#308 and conflated `balanced` and `braintree`.

**Comment by whit537** [comment]
Any further evidence to support that hypothesis?

**Comment by whit537** [comment]
Alright, what the heck were we doing on 308 and how did we end up with those logfiles?

**Comment by whit537** [comment]
Oh! Was it related to Balanced accounts that were migrate to Braintree?

**Comment by whit537** [comment]
Do we still have the scripts that produced these logfiles?

**Comment by whit537** [comment]
😕

```
/Users/whit537/personal/gratipay/logs/misc/308
total 88
drwxr-xr-x  13 whit537  staff    442 Jun  2 15:38 ./
drwxr-xr-x   9 whit537  staff    306 Mar 17  2016 ../
-rw-r--r--   1 whit537  staff   1342 Sep 30  2015 ally.csv
-rw-r--r--   1 whit537  staff   5769 Sep 30  2015 balanced.csv
-rw-r--r--   1 whit537  staff   4467 Sep 30  2015 balanced.monthly.csv
-rw-r-----@  1 whit537  staff   4555 Sep 22  2015 braintree.csv
-rw-r--r--   1 whit537  staff    136 Sep 23  2015 citizens-checking.csv
-rw-r--r--   1 whit537  staff    140 Sep 23  2015 citizens-money-market.csv
-rw-r--r--   1 whit537  staff  14068 Sep 30  2015 coinbase.csv
-rw-r--r--   1 whit537  staff   4307 Sep 30  2015 paypal.0.csv
-rw-r--r--   1 whit537  staff  11298 Sep 30  2015 paypal.1.csv
-rw-r--r--   1 whit537  staff  13524 Sep 30  2015 paypal.2.csv
drwxr-xr-x  14 whit537  staff    476 Jan  6  2016 raw/
[gratipay] $ ack -i --type=python braintree
[gratipay] $
```

**Comment by whit537** [comment]
Here's the migration: https://github.com/gratipay/gratipay.com/issues/3391.

**Comment by whit537** [comment]
[Prrrooommmiisssiiingggg](https://github.com/gratipay/gratipay.com/issues/3391#issuecomment-104433833) &hellip;

**Comment by whit537** [comment]
Notes from the bus ride ...

Did I overload https://github.com/gratipay/inside.gratipay.com/issues/308 with refunds? What was the ticket for refunds?

All of the `braintree.*` files under https://github.com/gratipay/inside.gratipay.com/issues/308 that have dates in them (only `post-back.log` doesn't) have only 2015 things for Braintree.

How about looking at old database backups to determine when these `braintree-cc` routes were entered?

Search for `braintree-cc` on GitHub? Can I search my gists for possible script treatment?

What are the patterns in how these routes were set? What are the relative ids of these routes? Can we use that to infer a date range or anything else about the creation or updating of these routes?

Huh! I ran a query to see the year of first exchange for these routes, and I'm seeing it only sparsely populated! Does `NULL` mean that there was an exchange route that was never used?

```sql
        SELECT er.id
             , username
             , address
             , (SELECT substring(timestamp::text from 0 for 5)
                  FROM exchanges
                 WHERE route=er.id
              ORDER BY timestamp asc
                 LIMIT 1
               ) AS year
          FROM exchange_routes er
          JOIN participants p
            ON p.id= er.participant
         WHERE network='braintree-cc'
      ORDER BY er.id asc;
```

Or are these routes that *should* be linked up to transactions but aren't yet?

Many of the addresses look like they were migrated from Balanced (`CCdeadbeef`), but there are plenty using native Braintree-format addresses as well.

These addresses in Balanced format—do we have a route for Balanced *and* a route for Braintree for the same address?

**Comment by kaguillera** [comment]
So an update for this is the PR under review to take care of plugging last remaining leak: ref under MassPay and add `ref` to record an exchange via #4518

**Comment by whit537** [comment]
Per IRL convo, we're getting to the point where I am going to need to be more involved in this ticket in order to continue making progress. Goal is to land #4518 asap, and then @kaguillera will work on other tickets while I am out traveling for the next couple months. We will revisit in the future.

**Comment by whit537** [comment]
I have a collection of old backups. Idea: crawl them and extract usernames over time. Use `claimed_time` to approximate a unique identifier prior to when we added `id`.

**Comment by kaguillera** [comment]
Sound good to me...but it will be tedious

**Comment by whit537** [comment]
@kaguillera and I talked IRL and are thinking that we should postpone this until we have revenue growth again, since without revenue growth we won't survive very long and backfilling exchanges won't matter. 

Well, but ... we should at least plug all leaks. The one remaining is the corrupt network issue (ticket description). What's up with that? Is it truly corrupt and are we continuing to introduce further corruption?

**Comment by whit537** [comment]
Re: corruption ... maybe due to overeager matching on `address` which largely persisted across the migration from Balanced to Braintree?

**Comment by whit537** [comment]
More apparent corruption with what route is linked to exchanges: https://github.com/gratipay/inside.gratipay.com/issues/1164#issuecomment-331213265.
