### ISSUE TITLE
Don't require reverification for package claiming

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#4520]
@rohitpaulk proposes at https://github.com/gratipay/gratipay.com/pull/4488#discussion_r122426725 and in [slack](https://gratipay.slackarchive.io/gratipay/page-100/ts-1497614829276345) that we drop the email dance when an email address is already verified, that we just send a notification ex post facto instead.

### Todo (from #4584)

- [ ] update claim action so it happens immediately (w/ notification to self)
- [ ] update bulk claiming so it happens immediately (w/ notification to self)
- [ ] implement verify action
- [ ] rip out claim-by-email wiring entirely

**Comment by whit537** [comment]
Notification to claimer would line up with notifying other maintainers as well: #4425.

**Comment by rohitpaulk** [comment]
There are two reasons I think this'll be a good idea: 

a) Easier for the user, one less step 
b) Decouples email verification from package claiming verification/notification - keeps our code simpler.

**Comment by whit537** [comment]
The potential drawback is security concerns around claiming packages. This would be offset by an after-the-fact notification but not quite as tight. Do we care?

**Comment by whit537** [comment]
> The potential drawback is security concerns around claiming packages.

It turns out through discussion culminating at https://github.com/gratipay/gratipay.com/issues/4557#issuecomment-324654121 that limiting the messages we send to unknown email accounts to just verifications is a better protection against phishing, because such verification spam is more of a known quantity to the general population and ignoring such messages is an already-learned behavior. Assigning any further agency to unsuspecting users is significantly more unsettling.

It would still be safer to require email confirmation for sensitive actions like linking packages (cf. #3969), but I agree that we shouldn't conflate claiming and verifying for unverified addresses.

> There are two reasons I think this'll be a good idea:

So security is a third reason.

**Comment by whit537** [comment]
> So security is a third reason.

Sorry, that's not actually fully relevant here. This ticket is about when someone has _already_ verified an email address. The security concern has to do with when an email address is unverified.
