### ISSUE TITLE
use id as primary key instead of username

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#835]
We're adopting a zero-downtime approach (https://github.com/gratipay/gratipay.com/pull/3864#issuecomment-162135818) here. Here are the basic steps for migrating from a column `foo` to `foo_id` without having to turn on maintenance mode:

| Step | `branch.sql` | Code changes to ... | Deploy which first? |
| :-- | :-- | :-- | :-- |
| 1 | add a new `foo_id` column | write to both `foo` and `foo_id` | `branch.sql` |
| 2 | backfill `foo_id` based on `foo` | read from `foo_id` | `branch.sql` |
| 3 | drop `foo` | no longer write to `foo` | code changes |

| After step ... | We are writing to ... | We are reading from ... |
| --- | --- | --- |
| 0 | `foo` | `foo` |
| 1 | `foo` and `foo_id` | `foo` |
| 2 | `foo` and `foo_id` | `foo_id` |
| 3 | `foo_id` | `foo_id` |
## Todo
- [ ] elsewhere
  - [ ] Writes
  - [ ] Reads
  - [ ] Dropped old column
- [x] payment_instructions
  - [x] Writes—#4058
  - [x] Reads—#4061
  - [x] Dropped old column—#4062
- [ ] payments
  - [ ] Writes
  - [ ] Reads
  - [ ] Dropped old column
- [ ] exchanges 
  - [ ] Writes
  - [ ] Reads
  - [ ] Dropped old column
- [ ] absorptions
  - [ ] Writes
  - [ ] Reads
  - [ ] Dropped old column
- [ ] takes
  - [ ] Writes
  - [ ] Reads
  - [ ] Dropped old column
- [ ] tips (can we just drop this table entirely?)
- [ ] teams.owner
  - [ ] Writes
  - [ ] Reads
  - [ ] Dropped old column
- [x] emails
  - [x] Writes - https://github.com/gratipay/gratipay.com/pull/3893
  - [x] Reads - https://github.com/gratipay/gratipay.com/pull/3896
  - [x] Dropped old column - https://github.com/gratipay/gratipay.com/pull/3898

See #503 and #287.
##

**Comment by whit537** [comment]
[IRC](https://botbot.me/freenode/gratipay/2015-04-02/?msg=35700951&page=2)

**Comment by Changaco** [comment]
We currently have 7 tables referencing `username` (`elsewhere`, `tips`, `transfers`, `exchanges`, `absorptions`, `takes`, `emails`) and 5 tables referencing `id` (`exchange_routes`, `community_members`, `statements`, `email_queue`, `balances_at`).

**Comment by whit537** [comment]
> I'd be surprised if there weren't an exploitable race condition hidden in there somewhere.

There are certainly race conditions, because our web app process(es) is (are) multi-threaded. A `Participant` object on one thread doesn't know about `username` changes in the database. Yes, the at the database level we shouldn't have any race conditions, but we do at the web app level.

**Comment by whit537** [comment]
Example: if one thread is changing a slug, and another thread is updating a payment instruction based on the slug, then the payment instruction will fail because it either won't find a Team with that slug, or (what's worse) it will silently fail by assigning the payment instruction to a Team that has managed to "steal" the old slug of the Team that is changing slugs.

**Comment by whit537** [comment]
Upgrading to `TeamX ★`.

**Comment by whit537** [comment]
@sammyshj Looking at https://github.com/gratipay/gratipay.com/issues/835#issuecomment-89250978, maybe `emails` would be a good table to start with? Want to put together a PR changing `emails.participant` to reference `participants.id` instead of `.username`?

**Comment by sammyshj** [comment]
Hello @whit537 ,
I want to work on this issue. Can you link me to some documentation that would help me get started on this?

**Comment by sammyshj** [comment]
@whit537 Yes, working on it right away!

**Comment by whit537** [comment]
@sammyshj Here's our [high-level description](https://github.com/gratipay/gratipay.com#modifying-the-database):

> We write SQL, specifically the [PostgreSQL variant](http://www.postgresql.org/docs/9.3/static/). We keep our database schema in [`schema.sql`](https://github.com/gratipay/gratipay.com/blob/master/sql/schema.sql), and we write schema changes for each PR branch in a `sql/branch.sql` file, which then gets run against production and merged into `sql/schema.sql` during deployment.

So, your PR should at least have a `sql/branch.sql` file. When you [run the test suite](https://github.com/gratipay/gratipay.com#testing-) you may find parts of the application that break due to the schema change, so your PR should address those issues as well.

Is that enough to get you started? What other questions can we answer?

**Comment by sammyshj** [comment]
Thanks for pointing out these things. If I face any problems later on regarding this issue, I will let you know.

**Comment by whit537** [comment]
Awesome, thanks @sammyshj! :-)

!m @sammyshj ← that's our [goofy way](http://motivate.im/) of saying, "You're doing a good job!" :)

**Comment by sammyshj** [comment]
@whit537 Currently emails.participant refers to participants, https://github.com/gratipay/gratipay.com/blob/master/sql/schema.sql#L320
Can you point out where it refers to participants.username?

**Comment by whit537** [comment]
It references the `participants` table, and without an explicit column specified, it references the primary key, which is `username`. We're not ready to change the primary key on `participants` yet.

**Comment by techtonik** [comment]
So, this change is required so that it is possible to change username without doing to much updates to DB, right?

**Comment by aandis** [comment]
> So, this change is required so that it is possible to change username without doing to much updates to DB, right?

Yes. That, along with the fact that it could result in an inconsistent data because of race conditions. See [issuecomment-136060460](https://github.com/gratipay/gratipay.com/issues/835#issuecomment-136060460)

**Comment by techtonik** [comment]
@aandis thanks. Now I understand more in DB design - why there is a hard requirement for an ID in many frameworks. =)

**Comment by aandis** [comment]
:+1:

**Comment by rohitpaulk** [comment]
I've added a list of tasks (copied from  https://github.com/gratipay/gratipay.com/issues/835#issuecomment-89250978) to the description of this ticket.

**Comment by aandis** [comment]
Naice! I didn't know you could do that. Github rocks. ;)

**Comment by whit537** [comment]
@kaguillera and I added some notes in the description about how to perform these changes with zero downtime.

**Comment by whit537** [comment]
We also reviewed "[Safe Operations For High Volume PostgreSQL](https://www.braintreepayments.com/blog/safe-operations-for-high-volume-postgresql/)."

**Comment by whit537** [comment]
Closing in light of our decision to [shut down Gratipay](https://gratipay.news/the-end-cbfba8f50981).

Thank you all for a great run, and I'm sorry it didn't work out! 😞  💃
